baseURL = 'https://solomonarul.github.io/'
languageCode = 'en-us'
title = "solomonarul.github.io"
theme = 'hugo-bearcub'

[params]
    domain = "solomonarul.github.io"
    homeTitle = "The website of all time."
    madeWith = "[Website](https://github.com/solomonarul/solomonarul.github.io) made with [Hugo](https://gohugo.io) using [BearCub](https://github.com/solomonarul/hugo-bearcub)."

[markup.goldmark.renderer]
    unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'