baseURL = 'https://solomonarul.github.io/'
languageCode = 'en-us'
title = "solomonarul.github.io"
theme = 'hugo-bearcub'

[params]
    domain = "solomonarul.github.io"
    homeTitle = "The psuedo-philosopher's place to rant."

[markup.goldmark.renderer]
    unsafe = true